# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-config
name: LXP
version: "1.1.0"
slug: lxp
description: LXP Bridge
url: "https://github.com/davewinwood/lxp_bridge_ha/tree/main/example"
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
init: false
options:
  message: "Hello LXP"
schema:
  message: "str?"
#image: "ghcr.io/home-assistant/{arch}-addon-example"
